---
- hosts: ctrl
  gather_facts: yes
  become: true
  tasks:
  - name: update & upgrade
    apt:
      upgrade: yes
      update_cache: yes
  - name: Add nginx stable repository from PPA and install its signing key on Ubuntu target
    apt_repository:
      repo: ppa:ansible/ansible
  - name: install ansible
    apt: 
      pkg: 
        - ansible
        - python3-pip
      update_cache: yes
      state: present