---
- hosts: db
  gather_facts: yes
  become: true
# install mongodb in db instance and ensure it's running
  tasks:
  - name: Update and upgrade apt packages
    apt:
      upgrade: yes
      update_cache: yes
  - name: installing mongo pre-requisites
    apt: pkg=mongodb state=present
  - name: allow 0.0.0.0
    ansible.builtin.lineinfile:
      path: /etc/mongodb.conf
      regexp: '^bind_ip = '
      insertafter: '^#bind_ip = '
      line: bind_ip = 0.0.0.0
  - name: restart and enable mongod
    service: name=mongodb state=restarted enabled=yes
