---
- hosts: web
  gather_facts: yes
  become: true
  tasks:
  - name: curl
    shell: curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  - name: nodejs
    apt: pkg=nodejs state=present