---
- hosts: web
  gather_facts: yes
  tasks:
  - name: start
    become_user: user
    shell: export DB_HOST=mongodb://3.249.73.94:27017/posts; cd app; node seeds/seed.js; npm install; screen -d -m npm start 